### PR TITLE
[MTDB-12288] Fix/make it snow

### PR DESCRIPTION
**Pull request by PorlyBe**
**Short Description:**

- snow on not connected.
- tweak polygon particles

**Figma Link (optional):**
N/A

**Screenshots (optional):**
N/A

**This PR is blocked by or a continuation of:**
PR#

### CODE REVIEW

**Review by micahpatng — COMMENTED** [review]
I was thinking maybe it's better to make the gradient leaning to lighter red instead of darker red? darker red looks like blood...halloween...

**Comment by PorlyBe** [comment]
Red to green gradient perhaps?

**Comment by micahpatng** [comment]
yes to red & green! if it fits haha

**Review by micahpatng — APPROVED** [review]
green it is!

**Pull request merged**
